export const SHOWCASE_V5 = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Decision light · Version 5</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#000;color:#dadfd9;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{display:flex;min-height:100vh;flex-direction:column;justify-content:center;align-items:center;padding:24px}main{width:min(1500px,100%)}canvas{display:block;width:100%;aspect-ratio:16/9;background:#000;border:1px solid #29312b;border-radius:12px;box-shadow:0 25px 100px #0006}.controls{display:flex;align-items:center;gap:8px;margin-top:18px}button,a{color:#cdd4cb;background:#1c221e;border:1px solid #354036;border-radius:6px;padding:10px 15px;cursor:pointer;font:inherit;text-decoration:none}button:hover,a:hover{background:#29312a}button:focus-visible,a:focus-visible{outline:2px solid #b6f276;outline-offset:3px}button:disabled{opacity:.4;cursor:wait}.primary{background:#b7ee80;color:#14230c;border-color:#b7ee80}.primary:hover{background:#caf49f}.note{margin-left:auto;font-size:11px;color:#849081}.time{font:11px monospace;color:#9cab97;min-width:66px}#message{min-height:22px;font-size:12px;color:#a9bd9e;margin:12px 0}a[hidden]{display:none}:fullscreen{padding:0;background:#000}:fullscreen canvas{border:0;border-radius:0;width:100vw;max-height:100vh;object-fit:contain}:fullscreen .controls,:fullscreen #message{display:none}@media(max-width:700px){body{padding:8px}.controls{flex-wrap:wrap}.note{width:100%;margin:6px 0}button,a{padding:9px 11px}}
</style></head><body><main><canvas id="stage" width="1920" height="1080" role="img" aria-label="On pure black, a white point pauses at fractal junctions, selects a luminous path, and accelerates toward a glowing destination. No text or interface appears in the animation."></canvas><input id="seek" aria-label="Animation position" type="range" min="0" max="11.99" step="0.01" value="0" style="width:100%;accent-color:#b6dfff;margin-top:12px"><div class="controls"><button id="play">Pause</button><button id="restart">Replay</button><button id="record" class="primary">Export video</button><a id="download" hidden>Download video</a><button id="fullscreen">Fullscreen</button><span id="time" class="time">00 / 12s</span><span class="note">Version 5 · decision light · 12-second loop</span></div><p id="message" role="status">Export records one complete loop as a video. Keep this tab visible while recording.</p></main><script>
'use strict';
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),DURATION=12;
let t=0,last=performance.now(),playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,recording=false,recorder=null,chunks=[],downloadUrl=null;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>v<.5?2*v*v:1-Math.pow(-2*v+2,2)/2;
let seed=1139;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
const points=[{x:160,y:910},{x:310,y:826},{x:426,y:685},{x:625,y:643},{x:745,y:489},{x:961,y:424},{x:1162,y:338},{x:1390,y:256},{x:1630,y:166}],branches=[],route=[],alternatives=[];
function branch(x,y,angle,len,depth,owner,hue){if(depth>8||len<2)return;const theta=angle+(random()-.5)*.38,nx=x+Math.cos(theta)*len,ny=y+Math.sin(theta)*len;branches.push({x,y,nx,ny,cx:x+Math.cos(angle)*len*.55,cy:y+Math.sin(angle)*len*.55,d:depth,owner,hue});const next=len*(.58+random()*.18);branch(nx,ny,theta+(random()-.5)*.28,next,depth+1,owner,hue);branch(nx,ny,theta+(random()<.5?-1:1)*(.45+random()*.7),next*(.65+random()*.24),depth+1,owner,hue)}
for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],angle=Math.atan2(b.y-a.y,b.x-a.x);route.push({x:a.x,y:a.y,nx:b.x,ny:b.y,cx:a.x+(b.x-a.x)*.4,cy:a.y+(b.y-a.y)*.08});for(let j=0;j<3;j++){const q=.2+j*.34,x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q;branch(x,y,angle+(j%2?1:-1)*(.55+random()*.9),90+random()*95,1,i,random()<.32?262:204)}}
// Every decision has three visible routes sharing the exact same junction.
for(let i=0;i<route.length;i++){
 const a=points[i],b=points[i+1],heading=Math.atan2(b.y-a.y,b.x-a.x),length=Math.hypot(b.x-a.x,b.y-a.y);
 for(const side of [-1,1]){
  const angle=heading+side*(.66+random()*.22),len=length*(.85+random()*.25);
  const e={x:a.x,y:a.y,nx:a.x+Math.cos(angle)*len,ny:a.y+Math.sin(angle)*len,cx:a.x+Math.cos(angle+side*.12)*len*.45,cy:a.y+Math.sin(angle+side*.12)*len*.45,owner:i};
  alternatives.push(e);branch(e.nx,e.ny,angle,len*.42,2,i,side<0?204:262);
 }
}
const durations=[1.14,.93,.75,.58,.43,.33,.24,.19],pauses=[.48,.4,.32,.26,.22,.18,.15,.12],selections=[.26,.23,.20,.18,.16,.14,.12,.10],stages=[];
let when=.55;for(let i=0;i<route.length;i++){stages.push({start:when,pause:pauses[i],selection:selections[i],duration:durations[i]});when+=pauses[i]+selections[i]+durations[i]}const arrival=when;
const layer=document.createElement('canvas');layer.width=1920;layer.height=1080;const lc=layer.getContext('2d');
function curve(c,e,p=1){const u=1-p,xx=u*u*e.x+2*u*p*e.cx+p*p*e.nx,yy=u*u*e.y+2*u*p*e.cy+p*p*e.ny;const cx=e.x+(e.cx-e.x)*p,cy=e.y+(e.cy-e.y)*p;c.beginPath();c.moveTo(e.x,e.y);c.quadraticCurveTo(cx,cy,xx,yy);return {x:xx,y:yy}}
function glow(c,x,y,r,power=1,hue=205){const g=c.createRadialGradient(x,y,0,x,y,r*9);g.addColorStop(0,'hsla('+hue+',100%,98%,'+power+')');g.addColorStop(.08,'hsla('+hue+',100%,92%,'+power+')');g.addColorStop(.3,'hsla('+hue+',90%,70%,'+power*.25+')');g.addColorStop(1,'hsla('+hue+',90%,70%,0)');c.fillStyle=g;c.beginPath();c.arc(x,y,r*9,0,7);c.fill()}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,1920,1080);let idx=stages.findIndex(s=>t<s.start+s.pause+s.selection+s.duration);if(idx<0)idx=7;const st=stages[idx],considering=t<st.start+st.pause,paused=t<st.start+st.pause+st.selection,p=clamp((t-st.start-st.pause-st.selection)/st.duration),move=curve(lc,route[idx],ease(p));const position=t<.55?{x:70+90*clamp(t/.55),y:980-70*clamp(t/.55)}:move;const finished=t>=arrival;const fade=t>10.8?1-clamp((t-10.8)/1.2):1;
// The camera follows gently; the destination remains visible inside the frame.
const zoom=.88+.16*clamp(t/arrival),follow=.15*clamp(t/arrival),tx=960-(960+(position.x-960)*follow)*zoom,ty=540-(540+(position.y-540)*follow)*zoom;
lc.clearRect(0,0,1920,1080);lc.save();lc.translate(tx,ty);lc.scale(zoom,zoom);
// Alternatives remain intact until the chosen route has lit up and travel begins.
function rejection(owner){const step=stages[owner];return clamp((t-step.start-step.pause-step.selection)/.3)}
for(const e of branches){const near=e.owner===idx;const alpha=((near&&considering?.64:.38)*(1-rejection(e.owner)*.82))*(1-e.d*.085)*fade;curve(lc,e);lc.strokeStyle='hsla('+e.hue+',85%,75%,'+alpha+')';lc.lineWidth=Math.max(.25,1.65-e.d*.18);lc.stroke();if(e.d<3)glow(lc,e.nx,e.ny,.75,alpha,e.hue)}
function candidate(e,owner){const near=owner===idx;const alpha=(near?.78:.48)*(1-rejection(owner)*.92)*fade;curve(lc,e);lc.strokeStyle='rgba(154,202,237,'+alpha+')';lc.lineWidth=1.65;lc.stroke()}
for(const e of alternatives)candidate(e,e.owner);
for(let i=0;i<route.length;i++){
 candidate(route[i],i);
 const step=stages[i],selected=t>=step.start+step.pause;
 if(selected){
  // Illuminate the entire choice while the point is still stationary.
  const strength=clamp((t-step.start-step.pause)/.075);
  curve(lc,route[i]);lc.strokeStyle='rgba(225,246,255,'+strength*.96*fade+')';lc.lineWidth=2.25;lc.stroke();
  if(i===idx&&paused) {const end=points[i+1];glow(lc,end.x,end.y,1.8,strength*.6*fade)}
 }
}
if(considering&&t>.55){const pausePhase=clamp((t-st.start)/st.pause);const a=points[idx];glow(lc,a.x,a.y,4+Math.sin(pausePhase*Math.PI)*2,.8*fade);lc.beginPath();lc.arc(a.x,a.y,10+pausePhase*19,0,Math.PI*2);lc.strokeStyle='rgba(156,199,255,'+(1-pausePhase)*.3*fade+')';lc.lineWidth=.7;lc.stroke()}
const dest=points.at(-1),bloom=finished?1:.15;glow(lc,dest.x,dest.y,finished?10+Math.sin((t-arrival)*1.4)*2:2.5,bloom*fade);if(finished){for(let i=0;i<38;i++){const ang=i*2.399,rad=18+Math.sqrt(i)*9;glow(lc,dest.x+Math.cos(ang)*rad,dest.y+Math.sin(ang)*rad,.55,(.25+.35*Math.sin(i+t)**2)*fade,i%4?205:265)}}
glow(lc,position.x,position.y,paused?3.6:4.4,fade);lc.restore();
ctx.save();ctx.globalCompositeOperation='screen';ctx.filter='blur(18px)';ctx.globalAlpha=.7;ctx.drawImage(layer,0,0);ctx.filter='blur(5px)';ctx.globalAlpha=.9;ctx.drawImage(layer,0,0);ctx.filter='none';ctx.globalAlpha=1;ctx.drawImage(layer,0,0);ctx.restore();document.getElementById('time').textContent=String(Math.floor(t)).padStart(2,'0')+' / 12s';}
function frame(now){const delta=(now-last)/1000;last=now;if(playing){t+=Math.min(delta,.1);if(t>=DURATION){if(recording){t=DURATION-.01;draw();stopRecording();playing=false;document.getElementById('play').textContent='Play'}else t%=DURATION}}draw();requestAnimationFrame(frame)}
document.getElementById('play').textContent=playing?'Pause':'Play';document.getElementById('play').onclick=()=>{if(recording)return;if(t>=DURATION-.1)t=0;playing=!playing;document.getElementById('play').textContent=playing?'Pause':'Play'};document.getElementById('restart').onclick=()=>{if(recording)return;t=0;playing=true;document.getElementById('play').textContent='Pause'};
function stopRecording(){if(recorder?.state==='recording')recorder.stop()}
document.getElementById('record').onclick=()=>{if(recording)return;const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(x=>window.MediaRecorder&&MediaRecorder.isTypeSupported(x));if(!mime||!canvas.captureStream){document.getElementById('message').textContent='Video export is not supported in this browser. Open this file in Chrome or use screen recording.';return}try{const stream=canvas.captureStream(60);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000});chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());recording=false;document.getElementById('record').disabled=false;document.getElementById('play').disabled=false;document.getElementById('restart').disabled=false;if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));const link=document.getElementById('download');link.href=downloadUrl;link.download='jev-decision-light-v5.'+(recorder.mimeType.includes('mp4')?'mp4':'webm');link.hidden=false;document.getElementById('message').textContent='Video ready. Download the 1920 × 1080 animation.';};recorder.onerror=()=>{document.getElementById('message').textContent='Recording failed. Try Chrome or use screen recording.';stopRecording()};t=0;last=performance.now();playing=true;recording=true;document.getElementById('record').disabled=true;document.getElementById('play').disabled=true;document.getElementById('restart').disabled=true;document.getElementById('download').hidden=true;document.getElementById('message').textContent='Recording one loop… Keep this tab visible for 12 seconds.';recorder.start(250)}catch(error){document.getElementById('message').textContent='Could not start video recording: '+error.message}};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('message').textContent='Fullscreen is unavailable in this browser.'}};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)document.getElementById('message').textContent='Recording is still active. Return to this tab to continue the animation.'});document.getElementById('seek').oninput=e=>{if(recording)return;t=Number(e.target.value);playing=false;document.getElementById('play').textContent='Play';draw()};requestAnimationFrame(frame);
</script></body></html>
`;
