export const SHOWCASE_V2 = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JEV — Refund decisions · Version 2</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#101211;color:#dadfd9;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{display:flex;min-height:100vh;flex-direction:column;justify-content:center;align-items:center;padding:24px}main{width:min(1500px,100%)}canvas{display:block;width:100%;aspect-ratio:16/9;background:#111412;border:1px solid #29312b;border-radius:12px;box-shadow:0 25px 100px #0006}.controls{display:flex;align-items:center;gap:8px;margin-top:18px}button,a{color:#cdd4cb;background:#1c221e;border:1px solid #354036;border-radius:6px;padding:10px 15px;cursor:pointer;font:inherit;text-decoration:none}button:hover,a:hover{background:#29312a}button:focus-visible,a:focus-visible{outline:2px solid #b6f276;outline-offset:3px}button:disabled{opacity:.4;cursor:wait}.primary{background:#b7ee80;color:#14230c;border-color:#b7ee80}.primary:hover{background:#caf49f}.note{margin-left:auto;font-size:11px;color:#849081}.time{font:11px monospace;color:#9cab97;min-width:66px}#message{min-height:22px;font-size:12px;color:#a9bd9e;margin:12px 0}a[hidden]{display:none}:fullscreen{padding:0;background:#111412}:fullscreen canvas{border:0;border-radius:0;width:100vw;max-height:100vh;object-fit:contain}:fullscreen .controls,:fullscreen #message{display:none}@media(max-width:700px){body{padding:8px}.controls{flex-wrap:wrap}.note{width:100%;margin:6px 0}button,a{padding:9px 11px}}
</style></head><body><main><canvas id="stage" width="1920" height="1080" role="img" aria-label="Illustrative refund workflow: CHOICE selects customer lookup and transactions, NOUL checks duplicate charges, CHOICE selects a refund, and NOUL checks completion."></canvas><div class="controls"><button id="play">Pause</button><button id="restart">Replay</button><button id="record" class="primary">Export video</button><a id="download" hidden>Download video</a><button id="fullscreen">Fullscreen</button><span id="time" class="time">00 / 19s</span><span class="note">Version 2 · timings and probabilities are illustrative</span></div><p id="message" role="status">Export records one complete loop as a video. Keep this tab visible while recording.</p></main><script>
'use strict';
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),DURATION=19;
let t=0,last=performance.now(),playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,recording=false,recorder=null,chunks=[],downloadUrl=null;
const C={bg:'#101411',text:'#edf4e7',dim:'#8a9d80',lime:'#c0fa7b',line:'#3a5030'};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>1-Math.pow(1-clamp(v),3);
function round(x,y,w,h,r=12){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function text(s,x,y,size=20,color=C.text,weight=400,align='left'){ctx.fillStyle=color;ctx.font=weight+' '+size+'px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.textAlign=align;ctx.fillText(s,x,y)}
function mono(s,x,y,size=14,color=C.dim,align='left'){ctx.fillStyle=color;ctx.font=size+'px ui-monospace,SFMono-Regular,monospace';ctx.textAlign=align;ctx.fillText(s,x,y)}
function path(points,progress=1,color=C.lime){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();const total=points.length-1;for(let i=0;i<=total;i++){if(i>progress*total){const f=progress*total-(i-1);ctx.lineTo(points[i-1][0]+(points[i][0]-points[i-1][0])*f,points[i-1][1]+(points[i][1]-points[i-1][1])*f);break}i?ctx.lineTo(...points[i]):ctx.moveTo(...points[i])}ctx.stroke()}
function card(x,y,w,h,title,sub,highlight=false){round(x,y,w,h);ctx.fillStyle=highlight?'#bfdc9a':'#1c261b';ctx.fill();ctx.strokeStyle=highlight?C.lime:'#3c5034';ctx.lineWidth=1;ctx.stroke();text(title,x+w/2,y+h/2+(sub?-3:8),sub?24:25,highlight?'#203119':C.text,550,'center');if(sub)mono(sub,x+w/2,y+h/2+25,14,highlight?'#3d552e':C.dim,'center')}
const rows=[
 {at:0.5,mode:'CHOICE',ms:'80 ms',question:'What should I do next?',choices:[['Look up customer','94%'],['Ask for more info','4%'],['Escalate','2%']],tool:'get_customer()',state:'Customer found',detail:'Account matched to the request.'},
 {at:2.6,mode:'CHOICE',ms:'75 ms',question:'What’s next?',choices:[['Get transactions','91%'],['Ask customer','5%'],['Escalate','4%']],tool:'get_transactions()',state:'Transactions loaded',detail:'Two matching charges found.'},
 {at:4.7,mode:'NOUL',ms:'',question:'Is there a duplicate charge?',choices:[['YES','97%'],['NO','3%']],tool:'duplicate = true',state:'Duplicate confirmed',detail:'Same invoice. Same amount.'},
 {at:6.8,mode:'CHOICE',ms:'',question:'What’s next?',choices:[['Refund duplicate','93%'],['Escalate','5%'],['Reject','2%']],tool:'issue_refund()',state:'Refund issued',detail:'Duplicate charge refunded.'},
 {at:8.9,mode:'NOUL',ms:'',question:'Task complete?',choices:[['YES','99%'],['NO','1%']],tool:'✓ DONE',state:'Request resolved',detail:'Refund recorded. Goal met.'}
];
function drawHeading(){text('Refund example',90,65,18,'#b4cba2');text('Demo · example values',1830,65,15,'#8ca17e',400,'right')}
function architecture(y,scale=1){const labels=['STATE','JEV','IF / ELSE','TOOL'],start=430;ctx.save();ctx.translate(960,y);ctx.scale(scale,scale);ctx.translate(-960,-y);labels.forEach((label,i)=>{const x=start+i*280;card(x,y,220,85,label,i===1?'DECISION':null,i===1);if(i<3)path([[x+225,y+42],[x+274,y+42]],1,'#7eaa57')});path([[1380,y+91],[1380,y+146],[540,y+146],[540,y+91]],1,'#66894b');mono('UPDATED STATE',960,y+176,16,'#a0bc86','center');ctx.restore()}
function draw(){const sequenceTime=t;const ending=sequenceTime>=12;const zooming=ending&&sequenceTime<12.65;const storyTime=zooming?11.99:sequenceTime;drawScene(storyTime,sequenceTime,zooming)}
function drawScene(t,sequenceTime,zooming){ctx.fillStyle=C.bg;ctx.fillRect(0,0,1920,1080);const glow=ctx.createRadialGradient(850,450,20,850,450,1100);glow.addColorStop(0,'#1e2d19');glow.addColorStop(1,C.bg);ctx.fillStyle=glow;ctx.fillRect(0,0,1920,1080);drawHeading();if(zooming){const z=ease((sequenceTime-12)/.65);ctx.save();ctx.translate(960,540);ctx.scale(1-.65*z,1-.65*z);ctx.translate(-960,-540);ctx.globalAlpha=1-z;}
if(t<12){text('“I was charged twice.”',90,148,51,C.text,550);text('“Can you refund the duplicate charge?”',92,192,27,'#b5c6a7');
const current=rows.findLastIndex(r=>t>=r.at),labels=['Find customer','Get transactions','Duplicate?','Issue refund','Complete?'];
// The entire chain is visible from the start; highlight follows the decision.
rows.forEach((r,i)=>{const x=90+i*354,y=260,w=310,h=108,active=i===current,complete=i<current||(i===4&&t>10.2);if(i<4){path([[x+w+7,y+54],[x+345,y+54]],1,i<current?C.lime:'#3b4b32');path([[x+335,y+47],[x+345,y+54],[x+335,y+61]],1,i<current?C.lime:'#3b4b32')}
ctx.save();if(active){ctx.shadowColor='#a2d862';ctx.shadowBlur=18}round(x,y,w,h,12);ctx.fillStyle=active?C.lime:complete?'#263c1d':'#1a2418';ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=active?'#ddffb0':complete?'#608844':'#37482e';ctx.stroke();mono((complete?'✓  ':String(i+1).padStart(2,'0')+'  ')+r.mode,x+20,y+ thirty(),15,active?'#304621':complete?'#add28b':'#7d926b');text(labels[i],x+20,y+74,26,active?'#203317':complete?'#d4e7c6':'#86977a',550);ctx.restore()});
if(current>=0){const r=rows[current],age=t-r.at,chosen=age>=.48,acted=age>=1.15,enter=ease(age/.25);ctx.save();ctx.globalAlpha=enter;
// Anchor the detail area to the active step without a separate state panel.
const anchor=245+current*354;path([[anchor,380],[anchor,408],[660,408],[660,444]],ease(age/.3),'#567d39');
mono('JEV '+r.mode+(r.ms?' · '+r.ms:''),140,481,17,C.lime);text(r.question,140,537, forty(),C.text,550);
r.choices.forEach(([label,pct],j)=>{const y=580+j* eighty(),unselected=chosen&&j>0;ctx.save();ctx.globalAlpha*=unselected?.8:1;round(140,y,960,64,9);ctx.fillStyle=chosen&&j===0?C.lime:'#263321';ctx.fill();text((chosen&&j===0?'✓  ':'')+label,163,y+42,27,chosen&&j===0?'#253a1a':'#d9e6ce',550);mono(pct,1074,y+42,25,chosen&&j===0?'#253a1a':'#9cae8c','right');ctx.restore()});
if(chosen){path([[1112,612],[1240,612]],ease((age-.48)/.5));mono('SELECTED ACTION',1330,542,16,C.dim);}
if(acted){const pop=ease((age-1.15)/.25);ctx.save();ctx.globalAlpha*=pop;ctx.translate(0,(1-pop)*18);card(1250,568,560,120,r.tool,null,current===4);text(r.state,1530,745,26,C.text,550,'center');text(r.detail,1530,787,21,C.dim,400,'center');ctx.restore()}
ctx.restore()}else{text('Request received → choose the first action',960,610,31,C.dim,450,'center')}
if(t>10.8){ctx.save();ctx.globalAlpha=ease((t-10.8)/.4);text('Agent orchestration is mostly decisions.',960,940,33,C.lime,550,'center');ctx.restore()}}

else{const age=t-12.65,enter=ease(age/.5);ctx.save();ctx.globalAlpha=enter;
// A single visual sentence replaces the slide-like stack of boxes.
text('A simpler way to orchestrate.',960,300, sixty(),C.text,550,'center');
const xs=[470,960,1450],labels=['Context','JEV','Action'];
for(let i=0;i<2;i++){const start=xs[i]+95,end=xs[i+1]-95,y=565;path([[start,y],[end,y]],1,'#405537');const progress=clamp((age-.7-i*.65)/.65);if(progress>0){path([[start,y],[start+(end-start)*progress,y]],1,C.lime);if(progress<1){ctx.save();ctx.shadowColor=C.lime;ctx.shadowBlur=18;ctx.fillStyle=C.lime;ctx.beginPath();ctx.arc(start+(end-start)*progress,y,5,0,Math.PI*2);ctx.fill();ctx.restore()}}}
xs.forEach((x,i)=>{const appear=ease((age-i*.15)/.4),active=i===1;ctx.save();ctx.globalAlpha*=appear;ctx.translate(x,565+(1-appear)*18);ctx.beginPath();ctx.arc(0,0,active?81: sixty(),0,Math.PI*2);ctx.fillStyle=active?C.lime:'#1d291a';ctx.fill();ctx.strokeStyle=active?'#d9ffa4':'#526844';ctx.lineWidth=1;ctx.stroke();if(active){text('JEV',0,12,36,'#203119',650,'center')}else{const symbol=i===0?'≡':'↗';text(symbol,0,12,34,'#b5cea0',500,'center')}ctx.restore();text(labels[i],x,706,27,active?C.text:'#b1c4a0',500,'center');if(active)text('Choose the next step',x,752,19,C.dim,400,'center')});
if(age>2.6){const a=ease((age-2.6)/.5);ctx.save();ctx.globalAlpha*=a;text('Decisions in the model. Control flow in code.',960,884,30,'#c5d5b7',450,'center');ctx.restore()}
ctx.restore()}

if(zooming)ctx.restore();
text('JEV decides. Tools execute.',90,1030,17,'#92aa7d');mono('VERSION 02 / REFUND',1830,1030,14,'#788e68','right');document.getElementById('time').textContent=String(Math.floor(sequenceTime)).padStart(2,'0')+' / 19s';}
function forty(){return 40}function eighty(){return 80}
function fifty(){return 50}function sixty(){return 60}function thirty(){return 30}
function frame(now){const delta=(now-last)/1000;last=now;if(playing){t+=Math.min(delta,.1);if(t>=DURATION){if(recording){t=DURATION-.01;draw();stopRecording();playing=false;document.getElementById('play').textContent='Play'}else t%=DURATION}}draw();requestAnimationFrame(frame)}
document.getElementById('play').textContent=playing?'Pause':'Play';document.getElementById('play').onclick=()=>{if(recording)return;if(t>=DURATION-.1)t=0;playing=!playing;document.getElementById('play').textContent=playing?'Pause':'Play'};document.getElementById('restart').onclick=()=>{if(recording)return;t=0;playing=true;document.getElementById('play').textContent='Pause'};
function stopRecording(){if(recorder?.state==='recording')recorder.stop()}
document.getElementById('record').onclick=()=>{if(recording)return;const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(x=>window.MediaRecorder&&MediaRecorder.isTypeSupported(x));if(!mime||!canvas.captureStream){document.getElementById('message').textContent='Video export is not supported in this browser. Open this file in Chrome or use screen recording.';return}try{const stream=canvas.captureStream(60);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000});chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());recording=false;document.getElementById('record').disabled=false;document.getElementById('play').disabled=false;document.getElementById('restart').disabled=false;if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));const link=document.getElementById('download');link.href=downloadUrl;link.download='jev-refund-decisions-v2.'+(recorder.mimeType.includes('mp4')?'mp4':'webm');link.hidden=false;document.getElementById('message').textContent='Video ready. Download the 1920 × 1080 animation.';};recorder.onerror=()=>{document.getElementById('message').textContent='Recording failed. Try Chrome or use screen recording.';stopRecording()};t=0;last=performance.now();playing=true;recording=true;document.getElementById('record').disabled=true;document.getElementById('play').disabled=true;document.getElementById('restart').disabled=true;document.getElementById('download').hidden=true;document.getElementById('message').textContent='Recording one loop… Keep this tab visible for 19 seconds.';recorder.start(250)}catch(error){document.getElementById('message').textContent='Could not start video recording: '+error.message}};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('message').textContent='Fullscreen is unavailable in this browser.'}};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)document.getElementById('message').textContent='Recording is still active. Return to this tab to continue the animation.'});requestAnimationFrame(frame);
</script></body></html>
`;
