export const SHOWCASE_V4 = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JEV — Decision field · Version 4</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#000;color:#dadfd9;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{display:flex;min-height:100vh;flex-direction:column;justify-content:center;align-items:center;padding:24px}main{width:min(1500px,100%)}canvas{display:block;width:100%;aspect-ratio:16/9;background:#000;border:1px solid #29312b;border-radius:12px;box-shadow:0 25px 100px #0006}.controls{display:flex;align-items:center;gap:8px;margin-top:18px}button,a{color:#cdd4cb;background:#1c221e;border:1px solid #354036;border-radius:6px;padding:10px 15px;cursor:pointer;font:inherit;text-decoration:none}button:hover,a:hover{background:#29312a}button:focus-visible,a:focus-visible{outline:2px solid #b6f276;outline-offset:3px}button:disabled{opacity:.4;cursor:wait}.primary{background:#b7ee80;color:#14230c;border-color:#b7ee80}.primary:hover{background:#caf49f}.note{margin-left:auto;font-size:11px;color:#849081}.time{font:11px monospace;color:#9cab97;min-width:66px}#message{min-height:22px;font-size:12px;color:#a9bd9e;margin:12px 0}a[hidden]{display:none}:fullscreen{padding:0;background:#000}:fullscreen canvas{border:0;border-radius:0;width:100vw;max-height:100vh;object-fit:contain}:fullscreen .controls,:fullscreen #message{display:none}@media(max-width:700px){body{padding:8px}.controls{flex-wrap:wrap}.note{width:100%;margin:6px 0}button,a{padding:9px 11px}}
</style></head><body><main><canvas id="stage" width="1920" height="1080" role="img" aria-label="Organic blue-violet filaments branch diagonally across black. Probability labels shimmer, peripheral branches dim, and a white point follows a luminous trunk."></canvas><input id="seek" aria-label="Animation position" type="range" min="0" max="8.99" step="0.01" value="0" style="width:100%;accent-color:#b6dfff;margin-top:12px"><div class="controls"><button id="play">Pause</button><button id="restart">Replay</button><button id="record" class="primary">Export video</button><a id="download" hidden>Download video</a><button id="fullscreen">Fullscreen</button><span id="time" class="time">00 / 9s</span><span class="note">Version 4 · luminous decision tree · 9-second loop</span></div><p id="message" role="status">Export records one complete loop as a video. Keep this tab visible while recording.</p></main><script>
'use strict';
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),DURATION=9;
let t=0,last=performance.now(),playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,recording=false,recorder=null,chunks=[],downloadUrl=null;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>1-Math.pow(1-clamp(v),3);
let seed=97;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
const segments=[],labels=[],trunk=[],W=1920,H=1080;
function twig(x,y,angle,length,depth,birth,hue){if(depth>8||length<3)return;const bend=(rand()-.5)*.38,theta=angle+bend,nx=x+Math.cos(theta)*length,ny=y+Math.sin(theta)*length;const seg={x,y,nx,ny,cx:x+Math.cos(angle)*length*.6,cy:y+Math.sin(angle)*length*.6,depth,birth,hue,main:false};segments.push(seg);if(depth<4&&rand()<.23)labels.push({x:nx,y:ny,p:['0.03','0.08','0.05','0.02','0.12'][Math.floor(rand()*5)],birth});const next=length*(.67+rand()*.11);twig(nx,ny,theta+(rand()-.5)*.24,next,depth+1,birth+.05,hue);twig(nx,ny,theta+(rand()<.5?-1:1)*(.42+rand()*.5),next*(.68+rand()*.18),depth+1,birth+.07,hue)}
let x=125,y=875;trunk.push({x,y});
for(let i=0;i<24;i++){const angle=-.46+Math.sin(i*.68)*.22,ln=70+rand()*12,nx=x+Math.cos(angle)*ln,ny=y+Math.sin(angle)*ln;segments.push({x,y,nx,ny,cx:x+Math.cos(angle-.13)*ln*.55,cy:y+Math.sin(angle-.13)*ln*.55,depth:0,birth:i*.065,main:true,hue:205});trunk.push({x:nx,y:ny});for(let side of [-1,1]){const angle2=angle+side*(.65+rand()*.7),length=80+rand()*90;twig(nx,ny,angle2,length,1,i*.065+.02,rand()<.28?260:205)}x=nx;y=ny}
const off=document.createElement('canvas');off.width=W;off.height=H;const oc=off.getContext('2d');
function line(c,e,width,color){c.beginPath();c.moveTo(e.x,e.y);c.quadraticCurveTo(e.cx,e.cy,e.nx,e.ny);c.lineWidth=width;c.strokeStyle=color;c.stroke()}
function dot(c,x,y,r,alpha=1){const g=c.createRadialGradient(x,y,0,x,y,r*7);g.addColorStop(0,'rgba(230,248,255,'+alpha+')');g.addColorStop(.09,'rgba(220,244,255,'+alpha+')');g.addColorStop(.3,'rgba(125,204,255,'+alpha*.25+')');g.addColorStop(1,'rgba(90,180,255,0)');c.fillStyle=g;c.beginPath();c.arc(x,y,r*7,0,7);c.fill()}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);oc.clearRect(0,0,W,H);const reveal=t<.6?0:(t-.6)*3.8,prune=clamp((t-4.4)/.65),travel=clamp((t-4.85)/1.7),endFade=t>8.1?1-clamp((t-8.1)/.9):1;
// Filaments have unequal lengths and angles; no grid, columns, or repeated geometry.
for(const e of segments){const born=clamp((reveal-e.birth)/.28);if(!born)continue;const pulse=Math.exp(-Math.pow((t-2.2-e.birth*.55)*3,2));const alpha=born*(e.main?.82:(.15+(.7-e.depth*.06)+pulse*.3)*(1-prune*.96))*endFade;const light=e.main?88:62+Math.max(0,5-e.depth)*4;line(oc,e,e.main?2.1:Math.max(.23,1.8-e.depth*.19),'hsla('+e.hue+',85%,'+light+'%,'+Math.max(0,alpha)+')');if((e.depth<4||e.main)&&born>.95)dot(oc,e.nx,e.ny,e.main?1.8:.65,alpha*.7)}
// Bloom is composited in layers; the fine unblurred pass stays crisp.
ctx.save();ctx.globalCompositeOperation='screen';ctx.filter='blur(13px)';ctx.globalAlpha=.6;ctx.drawImage(off,0,0);ctx.filter='blur(4px)';ctx.globalAlpha=.7;ctx.drawImage(off,0,0);ctx.filter='none';ctx.globalAlpha=1;ctx.drawImage(off,0,0);ctx.restore();
if(t>2&&t<4.9){ctx.save();ctx.globalAlpha=clamp((t-2)/.5)*clamp((4.9-t)/.5)*.8;ctx.font='14px ui-monospace,monospace';ctx.textAlign='center';labels.filter((_,i)=>i%3===0).forEach((l,i)=>{if(l.x>70&&l.x<1850&&l.y>80&&l.y<900){ctx.fillStyle=i%4===0?'#b6a1e8':'#83d7f5';ctx.fillText(l.p,l.x+12,l.y-12)}});ctx.restore()}
if(t<.6){dot(ctx,-20+145*ease(t/.6),875,4)}else{dot(ctx,125,875,3,endFade);if(t>4.85){const pos=travel*24,idx=Math.min(23,Math.floor(pos)),f=pos-idx,a=trunk[idx],b=trunk[idx+1],xx=a.x+(b.x-a.x)*f,yy=a.y+(b.y-a.y)*f;dot(ctx,xx,yy,4.5,endFade);for(let i=0;i<idx;i++){const e=segments.filter(e=>e.main)[i];line(ctx,e,2.3,'rgba(232,251,255,'+endFade+')')}}}
const caption=ease((t-6.7)/.7);ctx.globalAlpha=caption;ctx.font='300 27px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.textAlign='center';ctx.fillStyle='#d7e4ed';ctx.fillText('Agent orchestration, reduced to decisions.',960,985);ctx.strokeStyle='#788995';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(930,1011);ctx.lineTo(990,1011);ctx.stroke();ctx.font='14px -apple-system,sans-serif';ctx.fillStyle='#84919a';ctx.fillText('Jev',960,1041);ctx.globalAlpha=1;
document.getElementById('time').textContent=String(Math.floor(t)).padStart(2,'0')+' / 9s';}
function frame(now){const delta=(now-last)/1000;last=now;if(playing){t+=Math.min(delta,.1);if(t>=DURATION){if(recording){t=DURATION-.01;draw();stopRecording();playing=false;document.getElementById('play').textContent='Play'}else t%=DURATION}}draw();requestAnimationFrame(frame)}
document.getElementById('play').textContent=playing?'Pause':'Play';document.getElementById('play').onclick=()=>{if(recording)return;if(t>=DURATION-.1)t=0;playing=!playing;document.getElementById('play').textContent=playing?'Pause':'Play'};document.getElementById('restart').onclick=()=>{if(recording)return;t=0;playing=true;document.getElementById('play').textContent='Pause'};
function stopRecording(){if(recorder?.state==='recording')recorder.stop()}
document.getElementById('record').onclick=()=>{if(recording)return;const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(x=>window.MediaRecorder&&MediaRecorder.isTypeSupported(x));if(!mime||!canvas.captureStream){document.getElementById('message').textContent='Video export is not supported in this browser. Open this file in Chrome or use screen recording.';return}try{const stream=canvas.captureStream(60);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000});chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());recording=false;document.getElementById('record').disabled=false;document.getElementById('play').disabled=false;document.getElementById('restart').disabled=false;if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));const link=document.getElementById('download');link.href=downloadUrl;link.download='jev-decision-field-v4.'+(recorder.mimeType.includes('mp4')?'mp4':'webm');link.hidden=false;document.getElementById('message').textContent='Video ready. Download the 1920 × 1080 animation.';};recorder.onerror=()=>{document.getElementById('message').textContent='Recording failed. Try Chrome or use screen recording.';stopRecording()};t=0;last=performance.now();playing=true;recording=true;document.getElementById('record').disabled=true;document.getElementById('play').disabled=true;document.getElementById('restart').disabled=true;document.getElementById('download').hidden=true;document.getElementById('message').textContent='Recording one loop… Keep this tab visible for 9 seconds.';recorder.start(250)}catch(error){document.getElementById('message').textContent='Could not start video recording: '+error.message}};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('message').textContent='Fullscreen is unavailable in this browser.'}};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)document.getElementById('message').textContent='Recording is still active. Return to this tab to continue the animation.'});document.getElementById('seek').oninput=e=>{if(recording)return;t=Number(e.target.value);playing=false;document.getElementById('play').textContent='Play';draw()};requestAnimationFrame(frame);
</script></body></html>
`;
