export const SHOWCASE = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JEV — Decisions in motion</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#101211;color:#dadfd9;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{display:flex;min-height:100vh;flex-direction:column;justify-content:center;align-items:center;padding:24px}main{width:min(1500px,100%)}canvas{display:block;width:100%;aspect-ratio:16/9;background:#111412;border:1px solid #29312b;border-radius:12px;box-shadow:0 25px 100px #0006}.controls{display:flex;align-items:center;gap:8px;margin-top:18px}button,a{color:#cdd4cb;background:#1c221e;border:1px solid #354036;border-radius:6px;padding:10px 15px;cursor:pointer;font:inherit;text-decoration:none}button:hover,a:hover{background:#29312a}button:focus-visible,a:focus-visible{outline:2px solid #b6f276;outline-offset:3px}button:disabled{opacity:.4;cursor:wait}.primary{background:#b7ee80;color:#14230c;border-color:#b7ee80}.primary:hover{background:#caf49f}.note{margin-left:auto;font-size:11px;color:#849081}.time{font:11px monospace;color:#9cab97;min-width:66px}#message{min-height:22px;font-size:12px;color:#a9bd9e;margin:12px 0}a[hidden]{display:none}:fullscreen{padding:0;background:#111412}:fullscreen canvas{border:0;border-radius:0;width:100vw;max-height:100vh;object-fit:contain}:fullscreen .controls,:fullscreen #message{display:none}@media(max-width:700px){body{padding:8px}.controls{flex-wrap:wrap}.note{width:100%;margin:6px 0}button,a{padding:9px 11px}}
</style></head><body><main><canvas id="stage" width="1920" height="1080" role="img" aria-label="Scripted animation showing JEV choosing research, checking evidence, requesting a revision, and approving the result."></canvas><div class="controls"><button id="play">Pause</button><button id="restart">Replay</button><button id="record" class="primary">Export video</button><a id="download" hidden>Download video</a><button id="fullscreen">Fullscreen</button><span id="time" class="time">00 / 26s</span><span class="note">Scripted concept · no live model calls · 26-second loop</span></div><p id="message" role="status">Export records one complete loop as a video. Keep this tab visible while recording.</p></main><script>
'use strict';
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),DURATION=26;
let t=0,last=performance.now(),playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,recording=false,recorder=null,chunks=[],downloadUrl=null;
const C={bg:'#111412',paper:'#1a211c',line:'#35483a',text:'#eff5ea',dim:'#8b9c8a',lime:'#b9f578'};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>1-Math.pow(1-clamp(v),3);
function round(x,y,w,h,r=14){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function text(s,x,y,size=20,color=C.text,weight=400,align='left'){ctx.fillStyle=color;ctx.font=weight+' '+size+'px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.textAlign=align;ctx.fillText(s,x,y)}
function mono(s,x,y,size=14,color=C.dim){ctx.fillStyle=color;ctx.font=size+'px ui-monospace,SFMono-Regular,monospace';ctx.textAlign='left';ctx.fillText(s,x,y)}
const scenes=[
 {at:0,until:7,number:'01',question:'What should happen next?',context:'“Compare these products and recommend one.”',choices:['Research first','Write an answer','Ask the user'],pick:0,reason:'A recommendation needs evidence.',action:'RESEARCH AGENT',result:'Evidence collected',detail:'Sources, features, and pricing returned.',verb:'RESEARCH',back:'Evidence → JEV'},
 {at:7,until:14,number:'02',question:'Is the evidence sufficient?',context:'Research returned features — but no pricing.',choices:['Write the answer','Research pricing','Ask the user'],pick:1,reason:'Pricing is missing. Get the missing evidence.',action:'RESEARCH AGENT',result:'Missing evidence collected',detail:'Pricing added to the existing research.',verb:'RESEARCH PRICING',back:'Updated evidence → JEV'},
 {at:14,until:20,number:'03',question:'What should happen now?',context:'Features and pricing are ready.',choices:['Write the answer','Research more','Ask the user'],pick:0,reason:'The evidence is ready for a recommendation.',action:'WRITER AGENT',result:'Recommendation drafted',detail:'A comparison grounded in the evidence.',verb:'WRITE',back:'Draft → JEV'},
 {at:20,until:26,number:'04',question:'Does the result meet the goal?',context:'The draft compares products and recommends one.',choices:['Finish','Revise the draft','Escalate'],pick:0,reason:'The requested comparison is complete.',action:'DELIVER RESULT',result:'Goal met.',detail:'JEV chose to finish.',verb:'FINISH',back:'Workflow complete'}
];
function line(x1,y1,x2,y2,progress,colour=C.lime){ctx.save();ctx.strokeStyle='#354633';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle=colour;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x1+(x2-x1)*progress,y1+(y2-y1)*progress);ctx.stroke();if(progress>0&&progress<1){ctx.shadowColor=colour;ctx.shadowBlur=22;ctx.fillStyle=colour;ctx.beginPath();ctx.arc(x1+(x2-x1)*progress,y1+(y2-y1)*progress,6,0,7);ctx.fill()}ctx.restore()}
function draw(){ctx.fillStyle=C.bg;ctx.fillRect(0,0,1920,1080);const grad=ctx.createRadialGradient(700,480,20,700,480,1000);grad.addColorStop(0,'#22321e');grad.addColorStop(1,C.bg);ctx.fillStyle=grad;ctx.fillRect(0,0,1920,1080);
let index=scenes.findIndex(s=>t<s.until);if(index<0)index=3;const s=scenes[index],age=t-s.at;const reveal=ease(age/.45),chosen=age>=2.15,handed=age>=3.3,returned=age>=4.6;
mono('JEV / DECISION ORCHESTRATION',90, seventy(),16,'#b4c9a7');mono('SCRIPTED DEMO',1660,70,14,'#819277');text('JEV decides. Agents act.',90,150,57,C.text,550);
// A persistent history makes the revision visible across scenes.
const labels=['RESEARCH','RESEARCH PRICING','WRITE','FINISH'];for(let i=0;i<4;i++){const x=90+i*430;ctx.strokeStyle=i<=index?'#71934f':'#303b2a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,207);ctx.lineTo(x+375,207);ctx.stroke();mono(String(i+1).padStart(2,'0')+'  '+labels[i],x,238,15,i===index?C.lime:i<index?'#b0c49f':'#5b6a51')}
ctx.save();ctx.globalAlpha=reveal;ctx.translate(0,(1-reveal)*18);
// JEV is the large focal object. Options are discrete choices, never loading bars.
round(90,290,1030,608,24);ctx.fillStyle='#1a2419';ctx.fill();ctx.strokeStyle='#779b55';ctx.lineWidth=2;ctx.stroke();round(125,324,83,43,9);ctx.fillStyle=C.lime;ctx.fill();text('JEV',166,354,24,'#23351a',750,'center');mono('DECISION '+s.number,230,353,16,'#a7bd96');
text(s.question,125,423,40,C.text,550);text(s.context,125,467,23,'#b1bfa7');
s.choices.forEach((choice,i)=>{const y=505+i* ninety();const selected=chosen&&i===s.pick;const dimmed=chosen&&!selected;ctx.save();ctx.globalAlpha=dimmed?.28:1;round(125,y,955,72,11);ctx.fillStyle=selected?C.lime:'#263123';ctx.fill();ctx.strokeStyle=selected?'#d4ffa8':'#405039';ctx.lineWidth=1;ctx.stroke();text(selected?'✓':String(i+1),158,y+46,24,selected?'#253719':'#829674',600,'center');text(choice,190,y+47,28,selected?'#253719':'#e0e8d9',selected?650:450);if(selected)mono('SELECTED',940,y+45,17,'#334b23');ctx.restore()});
if(chosen){ctx.globalAlpha=ease((age-2.15)/.3);text(s.reason,128,837,24,'#c3d5b3',450);ctx.globalAlpha=1}else mono('CHOOSING THE NEXT ACTION',128,837,17,'#8ca17c');
// Only the selected choice gets a handoff. The receiving card pops up after selection.
if(chosen){const p=ease((age-2.35)/.85);const y=541+s.pick*90;ctx.strokeStyle='#67834e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(1080,y);ctx.lineTo(1157,y);ctx.lineTo(1157,575);ctx.stroke();line(1157,575,1260,575,p);if(p>.7){mono(s.verb,1150,480,14,C.lime)}}
if(handed){const pop=ease((age-3.3)/.45);ctx.save();ctx.globalAlpha=pop;ctx.translate(1490,575);const scale=.85+.15*pop+Math.sin(pop*Math.PI)*.025;ctx.scale(scale,scale);ctx.translate(-1490,-575);round(1260,425,550,300,20);ctx.fillStyle=returned?'#222f1d':'#1b211a';ctx.fill();ctx.strokeStyle=returned?'#91bf62':'#4d6240';ctx.lineWidth=1.5;ctx.stroke();mono(s.action,1295,478,19,'#a9c58f');text(returned?'✓ Result returned':'← Handoff received',1295,546,32,returned?C.lime:C.text,550);text(returned?s.result:'Execute the selected action.',1295,597,27,C.text,500);text(returned?s.detail:'Then return control to JEV.',1295,650,20,'#a2b195');ctx.restore()}
if(returned&&index<3){ctx.save();const p=ease((age-4.6)/.9);ctx.strokeStyle='#4c6939';ctx.lineWidth=2;ctx.setLineDash([6,7]);ctx.beginPath();ctx.moveTo(1540,730);ctx.lineTo(1540,928);ctx.lineTo(660,928);ctx.lineTo(660,902);ctx.stroke();ctx.setLineDash([]);const x=1540-880*p;ctx.fillStyle=C.lime;ctx.shadowColor=C.lime;ctx.shadowBlur=20;ctx.beginPath();ctx.arc(x,928,5,0,7);ctx.fill();ctx.shadowBlur=0;text(s.back,1250,964,20,'#b4ce9d',500,'center');ctx.restore()}
if(returned&&index===3){ctx.save();ctx.globalAlpha=ease((age-4.6)/.5);text('A decision at every handoff.',960,963,32,C.lime,550,'center');ctx.restore()}ctx.restore();
mono('ILLUSTRATIVE WORKFLOW · NO LIVE MODEL CALLS',90,1030,13,'#77886b');text('Question → choice → action → result → JEV',1830,1030,17,'#a1b68c',400,'right');document.getElementById('time').textContent=String(Math.floor(t)).padStart(2,'0')+' / 26s';}
function seventy(){return 70}function ninety(){return 90}
function frame(now){const delta=(now-last)/1000;last=now;if(playing){t+=Math.min(delta,.1);if(t>=DURATION){if(recording){t=DURATION-.01;draw();stopRecording();playing=false;document.getElementById('play').textContent='Play'}else t%=DURATION}}draw();requestAnimationFrame(frame)}
document.getElementById('play').textContent=playing?'Pause':'Play';document.getElementById('play').onclick=()=>{if(recording)return;if(t>=25.9)t=0;playing=!playing;document.getElementById('play').textContent=playing?'Pause':'Play'};document.getElementById('restart').onclick=()=>{if(recording)return;t=0;playing=true;document.getElementById('play').textContent='Pause'};
function stopRecording(){if(recorder?.state==='recording')recorder.stop()}
document.getElementById('record').onclick=()=>{if(recording)return;const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(x=>window.MediaRecorder&&MediaRecorder.isTypeSupported(x));if(!mime||!canvas.captureStream){document.getElementById('message').textContent='Video export is not supported in this browser. Open this file in Chrome or use screen recording.';return}try{const stream=canvas.captureStream(60);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000});chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());recording=false;document.getElementById('record').disabled=false;document.getElementById('play').disabled=false;document.getElementById('restart').disabled=false;if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));const link=document.getElementById('download');link.href=downloadUrl;link.download='jev-decisions-in-motion.'+(recorder.mimeType.includes('mp4')?'mp4':'webm');link.hidden=false;document.getElementById('message').textContent='Video ready. Download the 1920 × 1080 animation.';};recorder.onerror=()=>{document.getElementById('message').textContent='Recording failed. Try Chrome or use screen recording.';stopRecording()};t=0;last=performance.now();playing=true;recording=true;document.getElementById('record').disabled=true;document.getElementById('play').disabled=true;document.getElementById('restart').disabled=true;document.getElementById('download').hidden=true;document.getElementById('message').textContent='Recording one loop… Keep this tab visible for 26 seconds.';recorder.start(250)}catch(error){document.getElementById('message').textContent='Could not start video recording: '+error.message}};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('message').textContent='Fullscreen is unavailable in this browser.'}};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)document.getElementById('message').textContent='Recording is still active. Return to this tab to continue the animation.'});requestAnimationFrame(frame);
</script></body></html>
`;
